name: pantofitpremiumapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.0.6
  sphere_bottom_navigation_bar: ^1.0.0
  qr_flutter: ^4.0.0
  geolocator: ^7.0.3
  location: ^4.1.1
  async_controller: ^1.0.2
  http: ^0.13.3
  qr_code_scanner: ^0.5.1
  url_launcher: ^6.0.5
  flutter_barcode_scanner: ^2.0.0
  flutter_progress_hud: ^2.0.0
  modal_progress_hud: ^0.1.3
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - images/
    - images/icons/
    - images/partenaires/
